/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as OpenPositionsRouteImport } from './routes/open-positions'
import { Route as OrchestratorRouteImport } from './routes/orchestrator'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ReportsRouteImport } from './routes/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenPositionsRoute = OpenPositionsRouteImport.update({
  id: '/open-positions',
  path: '/open-positions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorRoute = OrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/candidates': typeof CandidatesRoute
  '/configuration': typeof ConfigurationRoute
  '/copilot': typeof CopilotRoute
  '/open-positions': typeof OpenPositionsRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/candidates': typeof CandidatesRoute
  '/configuration': typeof ConfigurationRoute
  '/copilot': typeof CopilotRoute
  '/open-positions': typeof OpenPositionsRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/candidates': typeof CandidatesRoute
  '/configuration': typeof ConfigurationRoute
  '/copilot': typeof CopilotRoute
  '/open-positions': typeof OpenPositionsRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/candidates'
    | '/configuration'
    | '/copilot'
    | '/open-positions'
    | '/orchestrator'
    | '/pipeline'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/candidates'
    | '/configuration'
    | '/copilot'
    | '/open-positions'
    | '/orchestrator'
    | '/pipeline'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/candidates'
    | '/configuration'
    | '/copilot'
    | '/open-positions'
    | '/orchestrator'
    | '/pipeline'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CandidatesRoute: typeof CandidatesRoute
  ConfigurationRoute: typeof ConfigurationRoute
  CopilotRoute: typeof CopilotRoute
  OpenPositionsRoute: typeof OpenPositionsRoute
  OrchestratorRoute: typeof OrchestratorRoute
  PipelineRoute: typeof PipelineRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-positions': {
      id: '/open-positions'
      path: '/open-positions'
      fullPath: '/open-positions'
      preLoaderRoute: typeof OpenPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrator': {
      id: '/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof OrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CandidatesRoute: CandidatesRoute,
  ConfigurationRoute: ConfigurationRoute,
  CopilotRoute: CopilotRoute,
  OpenPositionsRoute: OpenPositionsRoute,
  OrchestratorRoute: OrchestratorRoute,
  PipelineRoute: PipelineRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
